name: team_hack
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  bloc: ^8.1.2
  dot_navigation_bar: ^1.0.2
  flutter:
    sdk: flutter 
  flutter_bloc: ^8.1.3
  intl: ^0.18.1
  chat_bubbles: ^1.5.0

  supabase_flutter: ^1.10.25
  shared_preferences: ^2.2.2
  flutter_dotenv: ^5.1.0
  flutter_config: ^2.0.2

  google_maps_flutter: ^2.5.0
  geolocator: ^10.1.0

  geocoding: ^2.1.1
  location: ^5.0.3





  flutter_typeahead: ^5.0.1
  google_maps_webservice: ^0.0.20-nullsafety.5
  image_picker: ^1.0.4
  bloc_concurrency: ^0.2.2


#  flutter_google_maps_webservices: ^1.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  assets:
  - assets/json/dark_mode_style.json
  - assets/images/hackathon_image.png
  - .env
  - assets/images/proofile_image.jpg
  - assets/images/hackImage.png
  - assets/images/start_img.png
  - assets/images/design_filed.png
  - assets/images/business_analysis_filed.png
  - assets/images/data_analysis_filed.png
  - assets/images/information_security_filed.png
  - assets/images/network_filed.png
  - assets/images/programming_filed.png
  - assets/images/success_icon.png
  - assets/images/no_search_result.png
  - assets/placeHolderAvatar-noback.png

  uses-material-design: true

